name: Lint
on: push
jobs:
    format:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-python@v2
            - name: black
              uses: psf/black@master
              with:
                  args: .
            - name: Check for modified files
              id: git-check
              run: echo ::set-output name=modified::$(if git diff-index --quiet HEAD --; then echo "false"; else echo "true"; fi)
            - name: Push changes
              if: steps.git-check.outputs.modified == 'true'
              run: |
                  git config --global user.name 'jdha'
                  git config --global user.email 'jdha@github.com'
                  git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
                  git checkout `basename $GITHUB_REF`
                  git commit -am "Automated changes"
                  git push origin HEAD:`basename $GITHUB_REF`
